### ISSUE TITLE
Pathfolder

### ISSUE THREAD

**Issue by Atanu-S-Gupta** [OceanOptics/InvertLandsat_SST#1]
Can you give an example of using 'pathfolder' input in your function?

**Comment by guibourdin** [comment]
'pathfolder' should be a string of the path to the directory that contains the temperature band and the MTL file of the landsat scene you want to plot. Here is an example:
`pathfolder = '/Users/Username/Downloads/LC08_L2SP_011030_20230507_20230517_02_T1';`
I just noticed EarthExplorer is now providing more download options.
You can either download the entire product bundle and unzip it. The 'pathfolder' will then be the path to the unzipped folder.
Or you can download the option 'Level-2 Surface Temperature Bands' only, and copy all these files into a folder containing only the files from this specific image. In this case the 'pathfolder' will be the path of this folder.

**Comment by Atanu-S-Gupta** [comment]
![Screenshot 2023-05-27 112234](https://github.com/OceanOptics/getLandsatL2_SST/assets/127819694/94a4bf68-2c50-499d-9bb0-4e798f5574f3)
But I am receiving this error. The error comes from here-
![image](https://github.com/OceanOptics/getLandsatL2_SST/assets/127819694/a9dfba07-b4dd-496b-98ef-94859c2dc708)

**Comment by guibourdin** [comment]
I don't have this problem, so it's probably because we are using a
different versions of matlab. What version are you using?

Le sam. 27 mai 2023, 01:23, Atanu-S-Gupta ***@***.***> a
écrit :

**Comment by Atanu-S-Gupta** [comment]
@guibourdin I am using 2022b

**Comment by guibourdin** [comment]
I have just updated the line that crashed with Matlab 2022b.
Let me know if it solved it.

**Comment by Atanu-S-Gupta** [comment]
![image](https://github.com/OceanOptics/getLandsatL2_SST/assets/127819694/03cb252b-7163-4687-aa6f-8a529931a121)

**Comment by guibourdin** [comment]
Have you modified the mapping toolbox, as described in in the readme file?

The function 'gettiffinfo.m' from Matlab's mapping toolbox needs to be modified to recover accurate geolocalisation.
Follow instructions: [https://cosmojiang.wordpress.com/2018/04/02/matlab-geotiffread-for-multiple-layers/]

**Comment by guibourdin** [comment]
@Atanu-S-Gupta is it now working?
Can I close the issue?

**Comment by Atanu-S-Gupta** [comment]
Yes you can close the issue now. Sorry for the late reply.

**Comment by Atanu-S-Gupta** [comment]
Hi,  can you help me with the setting the land to Nan in band 10 data? It
called may be land masking. I am too much confused about the masking
algorithm. Thanks in advance

**Comment by guibourdin** [comment]
Hi,
You have to set the first optional argument ‘retrieve_land’ to true as follow:
[dt, lat, lon, temperature, fmask] = getLandsatL2_SST(pathfolder, true)
This will replace the land pixel by NaN.
Best,
Guillaume
